version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGPASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations

  app:
    build:
      context: .
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
    ports:
      - "${APP_PORT}:4000"
    command: go run cmd/app/main.go
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  db_data:
